#!/usr/bin/env bash
# Stops the 4-to_infinity_and_beyond process using kill
# Find the PID of the 4-to_infinity_and_beyond script
pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -n "$pid" ]; then
    kill "$pid"
fi
