#!/usr/bin/env bash
# Infinite loop that displays "To infinity and beyond" and handles SIGTERM signals

trap "echo 'I am invincible!!!'" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
